<?php
    $title = $this->translate('permits.page.title.check-answers');
    $this->headTitle($title);
?>

<div class="row ecmt">
    <div class="three-quarters">
        <div class="page-header">
            <p><a href="/permits/cabotage/<?php echo $id; ?>" class="back-link"> <?php echo $this->translate('permits.back-link'); ?> </a></p>
            <div class="page-header__wrapper">
                <h3 class="page-header__subtitle"> <?php echo $ref; ?></h3>
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($title); ?>
                </h1>
            </div>
        </div>

        <div class="field">
           <div class="table_wrapper">
                <table>
                    <thead>
                        <tr>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['licenceQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php echo str_replace(array("\r\n", "\n"), '<br />', $sessionData['licenceAnswer']); ?>
                            </td>
                            <td>
                                <a href="/permits/ecmt-licence/<?php echo $id; ?>">
                                    Change
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['meetsEuro6Question'] ?></h4>
                            </td>
                            <td>
                                <?php  echo $sessionData['meetsEuro6Answer']; ?>
                            </td>
                            <td>
                                <a href="/permits/euro6-emissions/<?php echo $id; ?>">
                                    Change
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['cabotageQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['cabotageAnswer'] ?>
                            </td>
                            <td>
                                <a href="/permits/cabotage/<?php echo $id; ?>">
                                    Change
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['restrictedCountriesQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php
                                    echo str_replace(array("\r\n", "\n"), '<br />', $sessionData['restrictedCountriesAnswer'])
                                ?>
                            </td>
                            <td>
                                <a href="/permits/restricted-countries/<?php echo $id; ?>">
                                    Change
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['tripsQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['tripsAnswer'] ?>
                            </td>
                            <td>
                                <a href="/permits/trips/<?php echo $id; ?>">
                                    Change
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['percentageQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['percentageAnswer'] ?>
                            </td>
                            <td>
                                <a href="/permits/international-journey/<?php echo $id; ?>">
                                    Change
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['specialistHaulageQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php echo str_replace(array("\r\n", "\n"), '<br />', $sessionData['specialistHaulageAnswer']) ?>
                            </td>
                            <td>
                                <a href="/permits/sector/<?php echo $id; ?>">
                                    Change
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $sessionData['permitsQuestion'] ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['permitsAnswer'] ?>
                            </td>
                            <td>
                                <a href="/permits/permits-required/<?php echo $id; ?>">
                                    Change
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="actions-container new-application--wrapper">
                <p><a href="/permits/declaration/<?php echo $id; ?>" class="action--primary large"><?php echo $this->translate('permits.button.confirm-and-continue'); ?></a></p>
                <p><a href="/permits"> <?php echo $this->translate('permits.button.save-return-to-overview'); ?> </a></p>
            </div>
        </div>
    </div>
</div>
