
                                <?php  echo $sessionData['meetsEuro6Answer']; ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_EURO6); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $this->translate($sessionData['cabotageQuestion']); ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['cabotageAnswer'] ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_CABOTAGE); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $this->translate($sessionData['restrictedCountriesQuestion']); ?></h4>
                            </td>
                            <td>
                                <?php
                                    echo nl2br($sessionData['restrictedCountriesAnswer'])
                                ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_COUNTRIES); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $this->translate($sessionData['tripsQuestion']); ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['tripsAnswer'] ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_TRIPS); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $this->translate($sessionData['percentageQuestion']); ?></h4>
                            </td>
                            <td>
                                <?php echo $this->translate($sessionData['percentageAnswer']); ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_INTERNATIONAL_JOURNEY); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $this->translate($sessionData['specialistHaulageQuestion']); ?></h4>
                            </td>
                            <td>
                                <?php echo nl2br($sessionData['specialistHaulageAnswer']) ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_SECTORS); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $this->translate($sessionData['permitsQuestion']); ?></h4>
                            </td>
                            <td>
                                <?php echo $sessionData['permitsAnswer'] ?>
                            </td>
                            <td>
                                <?php echo $this->changeAnswerLink(EcmtSection::ROUTE_ECMT_NO_OF_PERMITS); ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="actions-container new-application--wrapper">
                <p><a href="<?php echo $this->url('permits/' . EcmtSection::ROUTE_ECMT_DECLARATION, [], [], true); ?>" class="action--primary large"><?php echo $this->translate('permits.button.confirm-and-continue'); ?></a></p>
                <p><a href="<?php echo $this->url('permits') ?>"> <?php echo $this->translate('permits.button.save-return-to-overview'); ?> </a></p>
            </div>
        </div>
    </div>
</div>
