<?php
$title = 'Declaration ';
$this->headTitle($title);
?>
<p><?php echo $this->linkBack($this->backUrl); ?></p>

<h1 class="js-title"><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="two-thirds">
        <?php echo $this->translate('markup-ecmt-declaration'); ?>
        <div class="actions-container new-application--wrapper">
            <p><a href="/permits/payment" class="action--primary large"><?php echo $this->translate('submit-and-pay.button'); ?></a></p>
            <p><a href="/permits"> Cancel </a></p>
        </div
</div>
