<?php
    $title = $this->translate('permits.page.title.declaration');
    $this->headTitle($title);
?>

<div class="row">
    <div class="three-quarters">
        <div class="page-header">
            <p><a href="/permits/summary" class="back-link"> <?php echo $this->translate('permits.back-link'); ?> </a></p>
            <div class="page-header__wrapper">
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($title); ?>
                </h1>
            </div>
        </div>

        <div class="field">
            <div>
                <?php echo $this->translate('markup-ecmt-declaration'); ?>
            </div>
            <div class="actions-container new-application--wrapper">
                <p><a href="/permits/payment" class="action--primary large"><?php echo $this->translate('submit-and-pay.button'); ?></a></p>
                <p><a href="/permits"> <?php echo $this->translate('cancel'); ?> </a></p>
            </div>
        </div>
    </div>
</div>
