<?php
    $title = $this->translate('permits.page.title.declaration');
    $this->headTitle($title);

    /*
     * HIDDEN FORM TO SAVE TO DATABASE
     */

    $form->setAttribute('action', $this->url('permits', array('action' => 'fee')));

    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formHidden($form->get('intensity'));
    echo $this->formRow($form->get('sectors'));
    echo $this->formRow($form->get('restrictedCountries'));
    echo $this->formRow($form->get('restrictedCountriesList'));
?>

<div class="row">
    <div class="three-quarters">
        <div class="page-header">
            <p><a href="/permits/summary" class="back-link"> <?php echo $this->translate('permits.back-link'); ?> </a></p>
            <div class="page-header__wrapper">
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($title); ?>
                </h1>
            </div>
        </div>

        <div class="field">
            <div>
                <?php echo $this->translate('markup-ecmt-declaration'); ?>
            </div>
            <div class="actions-container new-application--wrapper">
                <p><?php echo $this->formSubmit($form->get('submit'));  ?></p>
                <!--<p><a href="/permits/payment" class="action--primary large"><?php //echo $this->translate('submit-and-pay.button'); ?></a></p>!-->
                <p><a href="/permits"> <?php echo $this->translate('permits.button.save-return-to-permits'); ?> </a></p>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
