<?php
    use Permits\View\Helper\EcmtSection;

$title = $this->translate('permits.page.fee.title');
$this->headTitle($title);
$application = $data['application'];
$translatorHelper = $this->getHelperPluginManager()->getServiceLocator()->get('Helper\Translation');
?>

<div class="row ecmt">
    <div class="two-thirds">
        <div class="page-header">
            <p><a href="<?php echo $this->url('permits') ?>" class="back-link"> <?php echo $this->escapeHtml($this->translate('common.link.back.label')); ?></a></p>
            <?php echo $this->formErrors($form); ?>

            <div class="page-header__wrapper">
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($this->translate('permits.page.fee-part-successful.title')); ?>
                    <?php
                    $markup = ($application['irhpPermitApplications'][0]['permitsAwarded'] === $application['permitsRequired']) ? 'markup-ecmt-fee-successful-hint' : 'markup-ecmt-fee-part-successful-hint';
                    echo $translatorHelper->translateReplace(
                            $markup,
                            [$application['irhpPermitApplications'][0]['permitsAwarded'],
                             $application['permitsRequired']]
                    ); ?>
                </h1>
            </div>
        </div>
        <div class="field">
            <div class="form-group form-steps ">
                <div class="form-group">
                    <?php echo $this->render('partials/read-only/list', ['items' => $application['items']]); ?>
                </div>
            </div>
            <?php echo $this->form($form); ?>
            <p><a href="<?php echo $this->url('permits') ?>"> <?php echo $this->escapeHtml($this->translate('permits.link.cancel.return.to.dashboard')); ?></a></p>
        </div>
    </div>
</div>
