<?php
    $title = $this->translate('permits.page.title.summary');
    $this->headTitle($title);
?>

<div class="row ecmt">
    <div class="three-quarters">
        <div class="page-header">
            <p><a href="/permits/cabotage" class="back-link"> <?php echo $this->translate('permits.back-link'); ?> </a></p>
            <div class="page-header__wrapper">
                <h1 class="js-title">
                    <?php echo $this->escapeHtml($title); ?>
                </h1>
            </div>
        </div>

        <div class="field">
           <div class="table_wrapper">
                <table>
                    <thead>
                        <tr>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <h4><?php echo $this->escapeHtml($sessionData['countriesQuestion']); ?></h4>
                            </td>
                            <td>
                                <?php
                                    if($sessionData['countries'] == 'No'){
                                        echo $this->escapeHtml($sessionData['countries']);
                                    }else {
                                        $count = 1;
                                        $listSize = count($sessionData['countries']);
                                        foreach ($sessionData['countries'] as $country) {
                                            if ($count == $listSize) {
                                                echo $this->escapeHtml($country);
                                            } else {
                                                echo $this->escapeHtml($country) . ', ';
                                            }
                                            $count++;
                                        }
                                    }
                                ?>
                            </td>
                            <td>
                                <a href="/permits/restricted-countries">
                                    Change
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $this->escapeHtml($sessionData['meetsEuro6Question']); ?></h4>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($sessionData['meetsEuro6']); ?>
                            </td>
                            <td>
                                <a href="/permits/euro6-emissions">
                                    Change
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h4><?php echo $this->escapeHtml($sessionData['cabotageQuestion']); ?></h4>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($sessionData['cabotage']); ?>
                            </td>
                            <td>
                                <a href="/permits/cabotage">
                                    Change
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="actions-container new-application--wrapper">
                <p><a href="/permits/declaration/<?php echo $this->escapeHtml($id); ?>" class="action--primary large"><?php echo $this->escapeHtml($this->translate('permits.button.accept-and-continue')); ?></a></p>
                <p><a href="/permits"> <?php echo $this->escapeHtml($this->translate('permits.button.save-return-to-permits')); ?> </a></p>
            </div>
        </div>
    </div>
</div>
